### ISSUE TITLE
Feature Request: Reject with message if link not found 

### ISSUE THREAD

**Issue by sveba** [guylabs/angular-spring-data-rest#7] opened 2015-03-21 16:50 UTC
Hi Guy,

upfront: You can close this one if this is not the desired behavior.

If I call processData for automatic link fetching with link name that doesn't exist in the given data, there is no feedback, that the link name is wrong. 

For example SpringDataRestAdapter.process(httpPromise, **'parent1'**, true) called in the example app just ignores that there is no **parent1** link and returns the data unmodified. 

I would expect this to result in an error like deferred.reject("The given link name: " + name + " can not be found") This would help to developers with messy API-Doc ;) 

BR,
Shari

**Comment by guylabs** [comment] 2015-03-27 10:23
Hi Shari,

sorry for my late response. I will add that in the next patch release. Is that ok for you? Maybe I will also add some more checks.

Thanks for mentioning and regards,

Guy

**Comment by guylabs** [comment] 2015-03-31 18:38
Hi Shari,

I just had once again a look at it and the problem is that I cannot add such a check because if we have the following response:

```json
{
    "_links": {
        "self": {
            "href": "http://localhost:8080/categories{?page,size,sort}",
            "templated": true
        },
        "testLink": {
            "href": "http://localhost:8080/categories/testLink"
        }
    },
    "_embedded": {
        "categories": [
            {
                "version": 0,
                "creationDate": 1406219870650,
                "modificationDate": 1406219870650,
                "name": "Test category 1",
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/categories/f974f5ef-a951-43b4-9027-4d2163216e54"
                    },
                    "parentCategory": {
                        "href": "http://localhost:8080/categories/f974f5ef-a951-43b4-9027-4d2163216e54/parentCategory"
                    }
                }
            },
            {
                "version": 0,
                "creationDate": 1406219884502,
                "modificationDate": 1406219884502,
                "name": "Test category 2",
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/categories/b5ba38d5-98d3-4579-8709-a28549406697"
                    },
                    "parentCategory": {
                        "href": "http://localhost:8080/categories/b5ba38d5-98d3-4579-8709-a28549406697/parentCategory"
                    }
                }
            }
        ]
    },
    "page": {
        "size": 20,
        "totalElements": 2,
        "totalPages": 1,
        "number": 0
    }
}
```

And lets say that we want to have the `parentCategory` link fetched. Then we first parse the `_links` property of the root object and there we do not have the `parentCategory` link name and we would reject the promise. But we do want to fetch the link name in the `_embedded` items.

So I think that this is not doable as if we would implement that, then all `_links` properties need to have the given link name.

But you are able to get all the resources with the following example:

```javascript
SpringDataRestAdapter.process(response).then(function(processedResponse) {
  var availableResources = processedResponse._resources();
});
```
Then the `availableResources` has the following format:

```json
[
    {
        "name":"self",
        "parameters": {
            "page": "",
            "size": "",
            "sort": ""
        }
    },
    {
        "name":"parentCategory"
    }
]
```

You can also read more on that in [this chapter](https://github.com/guylabs/angular-spring-data-rest#the-_resources-method-parameters-and-return-type) of the documentation.

I hope you understand the problem and can I then close the issue as won't fix?

Thanks and regards,

Guy

**Comment by guylabs** [comment] 2015-04-16 05:25
Hi Shari,

if you still have some questions please write a comment. I will close the issue due to inactivity.

Regards,

Guy

**Closed by guylabs** 2015-04-16 05:25 UTC
Labels: enhancement
